USE ROLE ACCOUNTADMIN;
USE DATABASE TRANSIT_PLANNING;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW V_ROUTE_PROFILE_MONTHLY AS
SELECT * FROM ROUTEPROFILE_JAN_2026
UNION ALL SELECT * FROM ROUTEPROFILE_FEB_2026
UNION ALL SELECT * FROM ROUTEPROFILE_MARCH_2026
UNION ALL SELECT * FROM ROUTEPROFILE_APRIL_2026
UNION ALL SELECT * FROM ROUTEPROFILE_MAY_2026
UNION ALL SELECT * FROM ROUTEPROFILE_JUNE_2026;

CREATE OR REPLACE VIEW V_ROUTE_PROFILE_SEASONAL AS
SELECT * FROM ROUTEPROFILE_SEASONAL_WINTER_2026
UNION ALL
SELECT * FROM ROUTEPROFILE_SEASONAL_SPRING_2026;

CREATE OR REPLACE VIEW V_REV_HOUR_MILE AS
SELECT
    COALESCE(h.year, m.year) AS year,
    COALESCE(h.month, m.month) AS month,
    COALESCE(h.month_number, m.month_number) AS month_number,
    COALESCE(h.route_short_name, m.route_short_name) AS route_short_name,
    COALESCE(h.direction, m.direction) AS direction,
    h.revenue_hours,
    m.revenue_miles,
    m.trip_count
FROM REVHOUR_ROUTES_2026 h
FULL OUTER JOIN REVMILE_ROUTES_2026 m
    ON h.year = m.year
    AND h.month_number = m.month_number
    AND h.route_short_name = m.route_short_name
    AND h.direction = m.direction;

GRANT USAGE ON DATABASE TRANSIT_PLANNING TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA TRANSIT_PLANNING.PUBLIC TO ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA TRANSIT_PLANNING.PUBLIC TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRANSIT_PLANNING.PUBLIC TO ROLE ACCOUNTADMIN;

GRANT SELECT ON ALL VIEWS IN SCHEMA TRANSIT_PLANNING.PUBLIC TO ROLE ACCOUNTADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TRANSIT_PLANNING.PUBLIC TO ROLE ACCOUNTADMIN;

SELECT * FROM V_ROUTE_PROFILE_MONTHLY LIMIT 10;
SELECT * FROM V_ROUTE_PROFILE_SEASONAL LIMIT 10;
SELECT * FROM V_REV_HOUR_MILE LIMIT 10;
